const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');
const User = require('./User');
const Hub = require('./Hub');

const Link = sequelize.define('Link', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  url: {
    type: DataTypes.TEXT,
    allowNull: false,
    validate: {
      isUrl: {
        msg: 'Must be a valid URL'
      },
      notEmpty: {
        msg: 'URL cannot be empty'
      }
    }
  },
  title: {
    type: DataTypes.STRING(255),
    allowNull: false,
    validate: {
      notEmpty: {
        msg: 'Title is required'
      },
      len: {
        args: [3, 255],
        msg: 'Title must be between 3 and 255 characters'
      }
    }
  },
  description: {
    type: DataTypes.TEXT,
    allowNull: true
  },
  category: {
    type: DataTypes.STRING(100),
    allowNull: true,
    validate: {
      isIn: {
        args: [['Technology', 'Education', 'Entertainment', 'Business', 'Health', 'Science', 'Sports', 'Other']],
        msg: 'Invalid category selected'
      }
    }
  },
  tags: {
    type: DataTypes.ARRAY(DataTypes.STRING),
    allowNull: true,
    defaultValue: []
  },
  clicks: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    allowNull: false,
    validate: {
      min: {
        args: [0],
        msg: 'Clicks cannot be negative'
      }
    }
  },
  isActive: {
    type: DataTypes.BOOLEAN,
    defaultValue: true,
    allowNull: false
  },
  isFavorite: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    allowNull: false
  },
  // CRITICAL: Rule combination operator (AND/OR) - Required for finals
  ruleOperator: {
    type: DataTypes.ENUM('AND', 'OR'),
    defaultValue: 'OR',
    allowNull: false,
    comment: 'Determines how multiple rules are combined: AND (all must match) or OR (any can match)'
  },
  // Rule matching metadata
  matchedRules: {
    type: DataTypes.ARRAY(DataTypes.INTEGER),
    allowNull: true,
    defaultValue: [],
    comment: 'IDs of rules that matched this link'
  },
  ruleScore: {
    type: DataTypes.FLOAT,
    allowNull: true,
    defaultValue: 0,
    comment: 'Overall score from rule matching (0-100)'
  },
  autoTagged: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    comment: 'Whether tags were automatically generated by rules'
  },
  userId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: 'Users',
      key: 'id'
    },
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE'
  },
  hubId: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: {
      model: 'Hubs',
      key: 'id'
    },
    onDelete: 'SET NULL',
    onUpdate: 'CASCADE'
  },
  metadata: {
    type: DataTypes.JSONB,
    allowNull: true,
    defaultValue: {},
    comment: 'Additional metadata like og:image, og:description, etc.'
  },
  lastClickedAt: {
    type: DataTypes.DATE,
    allowNull: true
  }
}, {
  tableName: 'links',
  timestamps: true,
  indexes: [
    {
      fields: ['userId']
    },
    {
      fields: ['hubId']
    },
    {
      fields: ['category']
    },
    {
      fields: ['isActive']
    },
    {
      fields: ['clicks']
    },
    {
      fields: ['createdAt']
    },
    {
      fields: ['ruleOperator']
    },
    {
      using: 'gin',
      fields: ['tags']
    }
  ]
});

// Instance methods
Link.prototype.incrementClicks = async function() {
  this.clicks += 1;
  this.lastClickedAt = new Date();
  await this.save();
  return this.clicks;
};

Link.prototype.addTag = async function(tag) {
  if (!this.tags.includes(tag)) {
    this.tags.push(tag);
    await this.save();
  }
  return this.tags;
};

Link.prototype.removeTag = async function(tag) {
  this.tags = this.tags.filter(t => t !== tag);
  await this.save();
  return this.tags;
};

Link.prototype.toggleFavorite = async function() {
  this.isFavorite = !this.isFavorite;
  await this.save();
  return this.isFavorite;
};

// CRITICAL: Rule evaluation method
Link.prototype.evaluateRules = async function(rules) {
  const matchedRuleIds = [];
  let totalScore = 0;

  for (const rule of rules) {
    const matches = rule.evaluate(this);
    if (matches) {
      matchedRuleIds.push(rule.id);
      totalScore += rule.priority || 10;
    }
  }

  // Apply rule operator logic
  let finalMatch = false;
  if (this.ruleOperator === 'AND') {
    // All rules must match
    finalMatch = matchedRuleIds.length === rules.length && rules.length > 0;
  } else {
    // At least one rule must match (OR)
    finalMatch = matchedRuleIds.length > 0;
  }

  this.matchedRules = matchedRuleIds;
  this.ruleScore = totalScore;
  await this.save();

  return { matched: finalMatch, ruleIds: matchedRuleIds, score: totalScore };
};

// Class methods
Link.getPopularLinks = async function(limit = 10) {
  return await Link.findAll({
    where: { isActive: true },
    order: [['clicks', 'DESC']],
    limit
  });
};

Link.getRecentLinks = async function(userId, limit = 20) {
  return await Link.findAll({
    where: { userId, isActive: true },
    order: [['createdAt', 'DESC']],
    limit
  });
};

Link.searchLinks = async function(userId, query) {
  const { Op } = require('sequelize');
  return await Link.findAll({
    where: {
      userId,
      [Op.or]: [
        { title: { [Op.iLike]: `%${query}%` } },
        { description: { [Op.iLike]: `%${query}%` } },
        { url: { [Op.iLike]: `%${query}%` } }
      ]
    },
    order: [['createdAt', 'DESC']]
  });
};

// Associations
Link.associate = function(models) {
  Link.belongsTo(models.User, {
    foreignKey: 'userId',
    as: 'user'
  });
  
  Link.belongsTo(models.Hub, {
    foreignKey: 'hubId',
    as: 'hub'
  });
};

module.exports = Link;
// Add these fields to your Link schema

qrCode: {
  type: DataTypes.TEXT,
  allowNull: true,
  comment: 'QR code data URL for the link'
},

shortUrl: {
  type: DataTypes.STRING(50),
  allowNull: true,
  unique: true,
  comment: 'Shortened URL from URL shortening service'
},

urlShortenerProvider: {
  type: DataTypes.ENUM('tinyurl', 'bitly', 'none'),
  defaultValue: 'none'
},

analytics: {
  type: DataTypes.JSON,
  defaultValue: {
    totalClicks: 0,
    uniqueVisitors: 0,
    clicksByDate: {},
    referrers: [],
    devices: { desktop: 0, mobile: 0, tablet: 0 },
    browsers: {},
    lastVisited: null
  },
  comment: 'Analytics data for the link hub'
},

offlineData: {
  type: DataTypes.JSON,
  defaultValue: {
    cachedAt: null,
    isOfflineAvailable: false,
    staticHtml: null
  }
},

themePreferences: {
  type: DataTypes.JSON,
  defaultValue: {
    autoDetectTheme: true,
    accentColor: '#22c55e',
    darkModeEnabled: false
  }
},

isStaticRendered: {
  type: DataTypes.BOOLEAN,
  defaultValue: false,
  comment: 'Whether the link hub has static HTML rendering'
}
